### ISSUE TITLE
Method parameters without type deceive Call Hierarchy and Search for References results

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1102]
See project attached to #1090. The presence of method `bar(String, Object, Object, String)` declared in `Test61` class (where the second and third parameters do not have an explicit declared type) causes results in Call Hierarchy and Search for References for `test61.MyBean.MyBean(SessionFactory, DetachedCriteria, List<Order>, BiConsumer<Session, ? super T>)` constructor calls to be wrong, even just a method name change can produce different results.

See https://github.com/groovy/groovy-eclipse/issues/1090#issuecomment-618855893 for all found cases.

**Comment by eric-milles** [comment]
Untyped parameters are not the issue.  Having two declarations for "bar"

    void bar()
    DetachedCriteria bar(String a, String, b, String c)

means there are two options for `bar('a','b','c')`, neither of which is an exact match.  When apparent typo is corrected, exact match is found easily and argument type `DetachedCriteria` is determined.  When method name is changed, only one option exists for "bar".

If you want to improve accuracy of type inference for constructor or method calls, you can assign argument expressions to local variables.  For example:
```groovy
SessionFactory sessionFactory= ...
DetachedCriteria criteria = bar('a','b','c')
Order[] orders = [Order.asc('x'), Order.asc('y')]
def bean = new Bean(sessionFactory, criteria, orders)
```
With this construction, the type inference engine visits and fully understands the arguments (now all variable expressions).  You can even use `def` for the three declarations with no degradation.

Visiting something like `new Bean(sessionFactory, bar('a','b','c'), Order.asc('x'), Order.asc('y'))`, the inference engine has to choose to visit the method or the arguments first.  To make closure parameters, closure delegation and SAM type coercion work, [the method is visited first](https://github.com/groovy/groovy-eclipse/blob/master/base/org.eclipse.jdt.groovy.core/src/org/eclipse/jdt/groovy/search/TypeInferencingVisitorWithRequestor.java#L1436).  So only basic type info can be determined from the inline argument expressions.

**Comment by eric-milles** [comment]
Another suggestion when you have a constructor situation like this:
```java
public class MyBean<T> {

	public MyBean(SessionFactory sessionFactory, DetachedCriteria baseCriteria, List<Order> defaultOrders, BiConsumer<Session, ? super T> postProcessor) {
	}

	public MyBean(SessionFactory sessionFactory, DetachedCriteria baseCriteria, List<Order> defaultOrders, Map<String, ? extends Iterable<String>> customSortFields) {
	}

	public MyBean(SessionFactory sessionFactory, DetachedCriteria baseCriteria, List<Order> defaultOrders, Map<String, ? extends Iterable<String>> customSortFields, BiConsumer<Session, ? super T> postProcessor) {
	}

	public MyBean(SessionFactory sessionFactory, DetachedCriteria baseCriteria, Order... defaultOrders) {
	}
}```

is to use a builder pattern.  Arguments can be given in any order, type inferencing is chunked up into smaller matches and other builder benefits.

```groovy
class MyBean<T> {
    static <T> MyBeanBuilder<T> builder() {
    }
    static class MyBeanBuilder<T> {
        MyBeanBuilder sessionFactory(SessionFactory f) { ...; return this; }
        MyBeanBuilder detachedCriteria(DetachedCriteria c) { ...; return this; }
        MyBeanBuilder defaultOrders(List<Order> orders) { ...; return this; }
        MyBeanBuilder defaultOrders(Order req, Order... opt) { ...; return this; }
        ...
        MyBean<T> build() {  }
    }
}

def bean = MyBeab.builder().sessionFactory(factory).detachedCriteria(bar('a','b','c')).defaultOrders(Order.asc('x'), Order.asc('y')).build()
```

Again, just a suggestion.  Wanted to put this out there in case any others are in this situation and are looking for options.

**Comment by mauromol** [comment]
Thank you for your detailed explanation Eric.
I see you closed this, however, don't you think we still have a bug here?

In Groovy assigning parameter values to variables and then call the constructor is completely equivalent to calling the constructor with inline parameters. So, if all worked correctly, there shouldn't be inconsistencies in Call Hierarchy and Search for References results, should be?

> Visiting something like new Bean(sessionFactory, bar('a','b','c'), Order.asc('x'), Order.asc('y')), the inference engine has to choose to visit the method or the arguments first. To make closure parameters, closure delegation and SAM type coercion work, the method is visited first. So only basic type info can be determined from the inline argument expressions.

But, after visiting the method, isn't its return type `DetachedCriteria`, just like it is if you first assign the result of the `bar(...)` call to a variable? Why do you say that "only basic type info can be determined" from the inline argument expression? 

The builder pattern is a good alternative/workaround, but not completely equivalent. I mean, using constructors you can declare some fields as final (because you set them on construction and never change them), which is something important to me. Having so many constructors is not very nice to see, but sometimes it happens because you enhance legacy code and you still want to maintain untouched the existing one and benefit from having final fields.

As a final note, now that you show me, I was thinking about this:

> Having two declarations for "bar"
> 
> ```groovy
> void bar()
> DetachedCriteria bar(String a, String, b, String c)
> ```
> 
> means there are two options for `bar('a','b','c')`, neither of which is an exact match.

First of all, where is `bar()` (with no parameters) defined? We don't have default parameters here and we only have one `bar(...)` declaration with 4 parameters... Shouldn't `bar('a', 'b', 'c') ` be just a call to an unknown method (and hence be underlined)? Using `@CompileStatic` indeed reveals this error. Probably this is the key to the whole problem here.

**Comment by eric-milles** [comment]
I understand that to the compiler there is equivalence.  We're not discussing a compiler issue here.  The type inference engine is trying to make the best sense it can of the runtime behavior from the static source.  This will never be 100% accurate, and in the case of methods and constructors, there is a conflict of interest between resolving argument expressions to understand what call is being made and resolving the call being made to understand what closure and lambda expressions map to.

There is a lot going on here with MyBean.  You have a class with a type parameter but no type argument passed to any of your constructor calls.  You have 4 overloads, one of which is a varargs.  You have multiple generic arguments and functional interfaces with closure expression arguments.  And you have inlined all the argument expressions, including maps, lists, arrays, closures and method calls.  I'm not saying you have to assign expressions to temp variables; I'm merely saying that you can help the IDE along by doing that.

I agree, the typo in your `DetachedCriteria` "bar" factory method was the key source of confusion.  I don't think there is anything more to do here.  I tested each of your scenarios without the typo and there were no problems with searching or call hierarchy.  If java index rebuild is not working, that is a JDT bug.

The builder pattern does not prevent you from having final fields; you can call a private constructor in the build method for one-time assignment of fields.  However, sticking with what you have is fully your business.

**Comment by mauromol** [comment]
> I agree, the typo in your `DetachedCriteria` "bar" factory method was the key source of confusion. I don't think there is anything more to do here. I tested each of your scenarios without the typo and there were no problems with searching or call hierarchy. If java index rebuild is not working, that is a JDT bug.

So, if we agree on this, don't you think that the `bar('a','b','c')` call should simply be underlined and rejected as unrecognised? Maybe this could also prevent it from interfering with Call Hierarchy and Search for References discovery and would bring to a more consistent behaviour of the IDE...
And, from a more practical (and important) point of view, would have helped me to see that I was doing an actual error...
