### ISSUE TITLE
Missing prefix suggestion for map-style constructor invocation when inserting a parameter in the middle

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#491]
Probably a special case of #331.

Consider this Java class:

```java
package test22;
public class MyBean {
	private String foo;
	private String bar;
	private String baz;
	public void setFoo(String foo) {	this.foo = foo; }
	public void setBar(String bar) {	this.bar = bar; }
	public void setBaz(String baz) {	this.baz = baz; }
}
```

and this Groovy class:

```groovy
package test22
class Test22 {
	public Test22() {
		def b = new MyBean(
				foo: 'foo',
				b|
				bar: 'bar')
	}
}
```

Invoke code assist at "|": no suggestion is given for `baz:`, while it is if you remove the leading "b".
It is also given if you add a comma after "|", but it's unnatural and, if you accept the proposal, you end up with a double comma (because of the completion behaviour described in #490).

**Comment by eric-milles** [comment]
Comma issue has been addressed separately.  You should be able to complete `new Bean(foo:abc, bar:xyz, b|)`.  There is parser recovery for the trailing comma and the trailing identifier is legal syntax.  `new Bean(foo:abc, b|\n bar:xyz)` is a syntax error and there is no parser recovery for it.

**Comment by mauromol** [comment]
I understand your point, but these are those small glitches that severely hurt productivity with Groovy.
It's not just `new Bean(foo:abc, b|\n bar:xyz)`, but also `new Bean(foo:abc, b| bar:xyz)`, that is whenever you need to edit the constructor call to add a new argument in the middle.

Fortunately, thanks to your hard work, Greclipse is getting better and better in this regard, however there are still multiple cases where parser recovery would help a lot, especially when you're used to JDT.

**Comment by eric-milles** [comment]
I agree, my whole reason for getting involved with the project was all the cases where I was used to doing something in the Java editor and the Groovy editor was not as complete.  In terms of the situations where things don't work the same, we just need to keep submitting issues and they will get fixed in as reasonable an order as I can manage.

**Comment by mauromol** [comment]
Just for curiosity, isn't it possible to request Groovy upstream patching to support downstream parser recovery through some kind of extension mechanism, so that you don't have to manually patch Groovy sources for every new Groovy version that is released?
How do other IDEs (like IDEA) deal with this problem?

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
I still see the exact same behaviour in 3.1.0.xx-201808212342-e47.
As an additional note, if I do this:

```groovy
def b = new MyBean(
			foo: 'foo',
			b|)
```

suggestions works as expected, but an exception is thrown: 

```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/D:/ws/47/DCS-FATTURAPA-trunk/

org.eclipse.jdt.ui
Error
Wed Aug 22 09:52:48 CEST 2018
Error retrieving proposal text.
Display string:
BaseDuration - groovy.time
Pattern:
MyBean(
			foo: 'foo',
			b

java.lang.StringIndexOutOfBoundsException: String index out of range: 29
	at java.lang.String.substring(Unknown Source)
	at org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal.getPatternMatchRule(AbstractJavaCompletionProposal.java:919)
	at org.eclipse.jdt.internal.ui.text.java.LazyJavaCompletionProposal.getStyledDisplayString(LazyJavaCompletionProposal.java:480)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.handleSetData(CompletionProposalPopup.java:861)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$8(CompletionProposalPopup.java:844)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$3.handleEvent(CompletionProposalPopup.java:597)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Table.checkData(Table.java:1189)
	at org.eclipse.swt.widgets.Table.wmNotifyChild(Table.java:6981)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5869)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:2025)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5423)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4899)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1657)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2199)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2454)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:587)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:453)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4941)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:6118)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2454)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:587)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:453)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4941)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:6118)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2454)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:587)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:453)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4941)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:6118)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.SendMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.SendMessage(OS.java:3313)
	at org.eclipse.swt.widgets.Table.setItemCount(Table.java:4794)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.setProposals(CompletionProposalPopup.java:1172)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:500)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1823)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer.doOperation(CompilationUnitEditor.java:184)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:84)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:287)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:527)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:577)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:385)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:331)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:88)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1271)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1078)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4962)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:364)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by mauromol** [comment]
Same behaviour (missing suggestion and exception as in my previous comment) with 3.1.0.xx-201808220545-e47.

**Comment by eric-milles** [comment]
For some reason this works in a script (or at the end of a script anyways).  At least this offers a point of comparison for recovery strategy/expectations.

**Comment by eric-milles** [comment]
In terms of error recovery, it appears to be the same for constructor, initializer, method or script.  "def b = new MyBean(foo: 'foo', b\n bar: 'bar')" is recovered as "b = new a.MyBean([foo:foo], b).call([bar: bar])".  It's odd, but it just works well enough for content assist.

The problem appears to be the exception encountered during content assist.  Is it still happening?  I am not getting that and so I am seeing proposals for the "bar" and "baz" named parameters.

**Comment by mauromol** [comment]
Testing with Greclipse 3.1.0.xx-201809202224-e48.

The original problem (not suggesting `baz` when invoking contest assist after `b|`) seems to be solved: the only small glitch is that, contrary to what happens if you start content assist without typing `b`, also `bar` is proposed (while it is already specified as the following parameter). But I don't think this is a huge problem, maybe we can open a new enhancement for that.

Also the exception described in my comment of August 22nd seems to be gone. 

So I'm closing this.
