### ISSUE TITLE
Groovy Eclipse compiler Not compiling Lombok Injtellij

### ISSUE THREAD

**Issue by wykapedia** [groovy/groovy-eclipse#583]
**Further detail:** https://github.com/mplushnikov/lombok-intellij-plugin/issues/478

**Groovy Eclipse Compiler version:** 2.9.3-01
**Groovy Eclipse Batch version:** 2.4.15-01

When compiling with maven, everything is compiled correctly with the annotation processor.  However, when compiling from within in Intellij, with the build / recompile action, the annotation processor does not seem to be invoked and the Lombok generated code is missing from the .class files.  I do have annotation processors enabled in compiler settings.

**Comment by eric-milles** [comment]
Can you provide a small sample project?  I'm not familiar with how IntelliJ triggers APT compilation or supplies the compiler options for it.

**Comment by wykapedia** [comment]
Hey @eric-milles, I will provide a small project to illustrate the issue.  Some updates on this.  If I have a clean `target` directory, none of the classes with Lombok annotations even get output.

**Comment by wykapedia** [comment]
Below are relevant IntelliJ settings:

**Java Compiler**
![image](https://user-images.githubusercontent.com/8344360/39997736-e598c95c-5751-11e8-9ef0-3471f842c2bc.png)

**Annotation Processors**
![image](https://user-images.githubusercontent.com/8344360/39997807-20f5138e-5752-11e8-912a-f2e6d6c27cfa.png)

**Comment by eric-milles** [comment]
For reference, here are the command-line options that are accepted by the batch compiler: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

And Groovy adds `-configScript` and `-indy`.

To define an annotation processor, use the `-processor` option.

**Comment by eric-milles** [comment]
In your case I think you would set:
```
-processor lombok.launch.Agent -processorpath /home/user/.m2/repository/org/projectlombok/lombok/1.16.18/lombok-1.16.18.jar -s generated
```

IntelliJ could supply these command-line settings based on your selections on the Annotation Processors screenshot.

**Comment by wykapedia** [comment]
Thanks for the recommendations @eric-milles.  I tried the latter and here is the error I am getting:

```txt
Information:Using Groovy-Eclipse to compile Java & Groovy sources
Information:Groovy-Eclipse: 2 problems (1 error, 1 warning)
Information:5/14/18 10:07 AM - Compilation completed with 2 errors and 1 warning in 8 s 337 ms
/home/docker/source/cirrus-apps/member-enrollment-file-processing-service/app/src/main/java/com/optum/cirrus/isl/member/memberenrollmentfileprocessing/repository/v1/EnrollmentFileMemberRepository.java
Error:Groovy-Eclipse: Internal compiler error: java.lang.IllegalAccessException: Class org.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager can not access a member of class lombok.launch.Agent with modifiers "" at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
/home/docker/source/cirrus-apps/member-enrollment-file-processing-service/app/src/test/java/com/optum/cirrus/isl/member/memberenrollmentfileprocessing/service/stream/v1/PrevalidateRequestPublisherSpec.groovy
Error:Groovy-Eclipse: Internal compiler error: java.lang.IllegalAccessException: Class org.eclipse.jdt.internal.compiler.apt.dispatch.BatchAnnotationProcessorManager can not access a member of class lombok.launch.Agent with modifiers "" at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
Warning:(10, -1) Groovy-Eclipse: Unsupported @SuppressWarnings("GroovyAssignabilityCheck")
```

**Comment by eric-milles** [comment]
What about `-processor lombok.launch.Main`?

**Comment by wykapedia** [comment]
Thanks for your help @eric-milles.  I am going to try a few more things.  I have been looking at the source code here: https://github.com/groovy/groovy-eclipse/blob/master/extras/groovy-eclipse-compiler/src/main/java/org/codehaus/groovy/eclipse/compiler/GroovyEclipseCompiler.java#L315

I know this is how the argument gets passed within the maven configuration.  I am going to attempt to pass this in Intellij as well and let you know how it goes.  Previously, I was trying:

`-javaagent:/path/to/lombok.jar`

Now, I will try:

`-javaAgentClass lombok.launch.Agent`

**Comment by wykapedia** [comment]
That didn't work.  Says its an unrecognized option.  How does the groovy eclipse maven configuration take it as an option, but groovy eclipse can't take it through `additional command line parameters` in IntelliJ?

**Comment by wykapedia** [comment]
Based on all of this, it seems as though, IntelliJ is not sending something correctly to the `Groovy-Eclipse` compiler.  Does that sound correct @eric-milles ?

**Comment by eric-milles** [comment]
The batch compiler operates based on its command line args.  If no APT agrs are set, lombok annotations are not processed.

**Comment by wykapedia** [comment]
I was looking at another issue: https://github.com/groovy/groovy-eclipse/issues/335, and it seems to be related?

**Comment by wykapedia** [comment]
@eric-milles which args are `APT`?

**Comment by eric-milles** [comment]
APT options are given here in the "Annotation processing" section:
https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

Re: the linked issue -- certainly there could be bugs with the APT integration.  If the proper command-line options are passed and the compilation behavior is incorrect, please open a new issue with a command-line-only example.  Lombok is a bit of a mixed bag as well since it requires APT support and adds the complication of separate javac and ecj agents.  Maven support for Lombok should be working.  But I've not tried batch compiler support.  I think you are heading into new territory there.

For this issue, IntelliJ integration is the main focus (from what I can gather).  I think the IntelliJ integration needs to be an issue on JetBrains bug tracker.

**Comment by eric-milles** [comment]
Also, for any bug submitted, a working Java example to compare to the non-working Groovy example would be extremely helpful.  I know it is a lot to ask but without much familiarity how all this stuff is supposed to behave, a working example is very valuable.

**Comment by kriegaex** [comment]
I don't understand why this was closed. There was a sample project and it was unresolved. The same problem still exists in brandnew IDEA 2020.1 after switching to Groovy-Eclipse. The IDE highlights e.g. `log` or generated setters and getters, i.e. it is aware of Lombok. My Maven build also works. But compilation from within IDEA fails with errors like "Groovy-Eclipse: log cannot be resolved".

**Comment by eric-milles** [comment]
What options are you sending to the groovy compiler adapter to enable Lombok APT during Java compile?  If you are sending none, then the issue is not in the compiler.  Project Lombok has specific integration for ecj (eclipse compiler for java, which is the technology behind groovy-eclipse-batch).  Has lombok looked at this and said the ecj integration is working as expected?  Is there a working Java example that can be compared to?  Without additional inputs such as these, this issue has reached a dead end.

**Comment by kriegaex** [comment]
> Is there a working Java example that can be compared to?

Actually my target class using Lombok annotations **is** a Java class because Lombok does not support Groovy. This is about Groovy-Eclipse being used as the default Java compiler instead of Javac, because the same works in Maven and I want my IDEA build to reflect my Maven settings as closely as possible.

Some background info:
1. In IDEA you can select a Java compiler for your project, e.g. Javac, AspectJ, Groovy-Eclipse.
2. On another IDEA settings page you can generally enable annotation processing.
3. There also is a Lombok plugin which always gets updated quickly after each IDEA release. This plugin makes sure that IDEA uses Lombok without specifying any further settings such as Java agents or APT classes in case of Javac having been selected in (1). The same used to work for me when Groovyc was selected as the Java compiler until the latest 2019.x version. Now after I upgraded to 2020.x it no longer works.

Having said all this, I would understand if you would point me to JetBrains (IDEA) or the maintainer of the IDEA Lombok plugin first, but the reason why I was asking here is that even if it does not work automatically, adding the right settings for the Groovy-Eclipse compilation process manually at least ought to be a temporary workaround. After reading what other people wrote above, I think that the question which settings **are** the correct ones still has not been answered. It looks like only Lombok specialists or only Groovy-Eclipse specialists alone cannot answer, so I am asking in multiple places in order to bring people with different knowledge together and finally resolve this in a joint effort.

**Comment by eric-milles** [comment]
What I'm asking for in terms of "Java example" is a sample project that uses the eclipse compiler for java (ecj), not the maven java compiler and not the groovy-eclipse compiler.  This would give me a basis for comparison.  If Lombok supports ecj in this scenario, then the groovy-eclipse compiler (an extension of ecj) failing would demonstrate that this is a problem to be resolved here.

I cannot troubleshoot IntelliJ problems since I don't have that environment and don't plan on setting it one up.  Lombok has been very tricky to work with since it has special handling for different compilers and IDE vs. command-line usage and logs very little diagnostic information.

**Comment by kriegaex** [comment]
Thanks, but that is not very helpful.

I got this running from the command line (Windows cmd.exe):

```java
import lombok.*;

@Builder
@Getter
@Setter
@EqualsAndHashCode
@ToString
public class ListItem {
  private String itemName;
  private String itemValue;

  public static void main(String[] args) {
    ListItem item = new ListItemBuilder()
      .itemName("mood")
      .itemValue("bored")
      .build();
    System.out.println(item);
  }
}
```

```none
java -javaagent:c:\Users\XXX\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar=ECJ -jar c:\Users\XXX\.m2\repository\org\codehaus\groovy\groovy-eclipse-batch\2.5.7-01\groovy-eclipse-batch-2.5.7-01.jar -8 -proc:none ListItem.java
```

Version with inserted line breaks:

```none
java
  -javaagent:c:\Users\XXX\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar=ECJ
  -jar c:\Users\XXX\.m2\repository\org\codehaus\groovy\groovy-eclipse-batch\2.5.7-01\groovy-eclipse-batch-2.5.7-01.jar
  -8
  -proc:none
  ListItem.java
```
It seems to be next to impossible to get it working in IntelliJ. There I need to set up
* `-proc:none` in Groovy Eclipse additional CLI parameters
* all of this for general Java compiler VM options (in one line):
  * `-Xbootclasspath/p:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar;c:/Users/alexa/.m2/repository/org/eclipse/jdt/org.eclipse.jdt.core/3.17.0/org.eclipse.jdt.core-3.17.0.jar`, i.e. additionally to lombok also Eclipse JDT Core because if I only add the path to `groovy-eclipse-batch-2.5.7-01.jar` it will complain about some missing JDT core classes.
  * `-javaagent:c:\Users\Alexa\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar=ECJ`

Now I can compile the above sample Java file as a single file, but as soon as I rebuild my whole project, compilation fails because it seems to think that some Java file paths are compiler options.

I know, @eric-milles, you cannot help me or are not much interested in investing a lot of effort to set up IntelliJ IDEA, but maybe my post helps others pick up the ball and take it from here, maybe solving my follow-up problem too.

**Comment by sabinaradha** [comment]
I am also facing exact same issue with Intellij.

**Comment by VolodymyrShpynta** [comment]
> I am also facing exact same issue with Intellij.

@sabinaradha try to use Javac compiler instead of Groovy-Eclipse.
I've faced the same issue with Groovy-Eclipse compiler. And I've figured out the Javac compiler works pretty well and could be used instead of Groovy-Eclipse even to run groovy tests.

My IntelliJ IDEA version:
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020

**Comment by YevhenPiskun** [comment]
Also faced with this issue. Here is my configuration:

IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to Playtika LTD.

Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1965M
Cores: 8
Non-Bundled Plugins: com.alayouni.ansiHighlight, Lombook Plugin, com.thoughtworks.gauge, com.intellij.ideolog, MavenRunHelper

**Comment by HossamMohammed094** [comment]
same here, any update with this issue ?

**Comment by digaobarbosa** [comment]
Same here

**Comment by longbe00** [comment]
same here
